# Generated by Django 2.2 on 2020-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'question_tbl',
                'managed': False,
            },
        ),
    ]
