# Generated by Django 2.2 on 2020-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'notice_tbl',
                'managed': False,
            },
        ),
    ]
