# Generated by Django 2.2 on 2020-10-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticetbl',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
