# Generated by Django 2.2 on 2020-10-19 03:37

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTbl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'admin_tbl',
                'managed': False,
            },
            managers=[
                ('objects', User.models.UserManager()),
            ],
        ),
    ]
