# Generated by Django 2.2 on 2020-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'member_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('access', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=4)),
                ('grade', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('languages', models.CharField(blank=True, max_length=11, null=True)),
                ('report_tblcol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'report_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=12)),
                ('self_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('auth_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_tbl',
                'managed': False,
            },
        ),
    ]
